### PR TITLE
Make resolve-import-conflicts return a status code

### PR DESCRIPTION
**Pull request by mernst**

### CODE REVIEW

**Comment by benedikt-schesch** [comment]
@mernst Is it correct that the function `issubsequence` in `src/scripts/merge_tools/resolve-conflicts.py` takes as argument two lists of strings?

**Comment by mernst** [comment]
@benedikt-schesch Thanks for the improvements!
`issubsequence` (which I just renamed to `is_subsequence` to be more Pythonic) takes arbitrary sequences as input.  It does work for strings, but it is generic over the type of list elements.

**Comment by benedikt-schesch** [comment]
@mernst If you set the type hints to string you can see that one of the function calls does call it with a list of strings, so I am not sure if the script is correct currently.

**Comment by mernst** [comment]
@benedikt-schesch I think that is OK:  the function works on any type of list, including a list of strings, and it's called with a list of strings.  Is there a problem that I don't see?

**Comment by benedikt-schesch** [comment]
Then we're all good

**Pull request merged**
