### PR TITLE
Add `X_plus.sh` scripts that fix up the result of `X.sh`

### PR DESCRIPTION
**Pull request by mernst**
Merge after #352.  (Or, merge instead of #352, after approving #352, in order to avoid merge conflicts.)
Before merging this, please run the pipeline to update all the results.  That should also make CI pass.

Here is the motivation for this pull request:  It is important to update the results of strategy "X" according to the results of "X + plume-lib-fixups", where "plume-lib-fixups" is guaranteed to be correct.  This pull request adds "adjacent + plume-lib-fixups", in order to enable proper adjustment of the results of "adjacent".

### CODE REVIEW

**Comment by benedikt-schesch** [comment]
@mernst I think you understand wrongly what import, adjacent and version numbers are. It's not a x+plumelib strategy but a partial way of running plumelib.

**Comment by mernst** [comment]
> @mernst I think you understand wrongly what import, adjacent and version numbers are. It's not a x+plumelib strategy but a partial way of running plumelib.

Please see the email thread.  You are confusing implementation details with concepts.

**Comment by benedikt-schesch** [comment]
@mernst There is no diff here anymore after reverting test results and merging main. I am not sure what exactly you want but it would be great to add the missing script here.

**Comment by mernst** [comment]
I think this is ready to be merged.  How do I update the reproducibility tests?

**Comment by benedikt-schesch** [comment]
@mernst First plumelib needs to be fixed and then we can add new tools

**Comment by mernst** [comment]
Can you tell me what is necessary and how I can double-check it?  I think this pull request resolves the problem with plume-lib not running, which I corrected in https://github.com/benedikt-schesch/AST-Merging-Evaluation/pull/353/commits/083d6d4346d17872e2b914768d325468f3c4463e.

**Comment by benedikt-schesch** [comment]
@mernst This branch does worse than #355 which simply uses an older hash and both branches do worse than #358 which simply uses the same older hash for pluemlib but it uses the main branch code. I look at git merge ort for this comparison.

**Pull request merged**
