### PR TITLE
V2 update

### PR DESCRIPTION
**Pull request by benedikt-schesch**

### CODE REVIEW

**Comment by benedikt-schesch** [comment]
Todo:

- [ ] Create a new general Repository class to handle merging, testing and checkouts. 
- [ ] Refactor `validate_repos.py`
- [ ] Add Merge Differ
- [ ] Refactor `merge_tester.py`
- [ ] Refactor `latex_output.py`
- [ ] Remove all unnecessary files
- [ ]  Refactor `README`
- [ ] (Optional) Type the schema of panda frames
- [ ] Update Test Case

**Comment by benedikt-schesch** [comment]
@mernst The code is basically finished. One last problem is inside the CI/CD pipeline for some reason the sha256 results are different for JSCover inside of the CI/CD pipeline. I can't explain it and I have tried on 3 different machines to reproduce this error yet on all these machines the small test passes and the hashes are exactly the same. Do you have any idea how we could reproduce this problem or if there is a reasonable explanation that allows us to remove JSCover from the test suite?

**Comment by mernst** [comment]
`table_feature_main_summary.tex` and `table_summary.tex` contain underscores that LaTeX will choke on.  I would replace all underscores by hyhens before writing them to LaTeX output.

**Comment by benedikt-schesch** [comment]
@mernst Good to merge?

**Pull request merged**
